export const TAG = {
  DIVIDEND: 'DIVIDEND',
  SALARY: 'SALARY',
  SIPP: 'SIPP',
  ACCOUNTANT: 'ACCOUNTANT',
  BUSINESS_INSURANCE: 'BUSINESS_INSURANCE',
  LIFE_INSURANCE: 'LIFE_INSURANCE',
  TRAIN: 'TRAIN',
  FOOD: 'FOOD',
  MOBILE: 'MOBILE',
  VAT: 'VAT',
  WEB_HOSTING: 'WEB_HOSTING',
  NETFLIX: 'NETFLIX',
  SPOTIFY: 'SPOTIFY',
  GOOGLE: 'GOOGLE',
  MICROSOFT: 'MICROSOFT',
  GITHUB: 'GITHUB',
  JETBRAINS: 'JETBRAINS',
  CHOOSY_MOVIE_RESEARCH: 'CHOOSY_MOVIE_RESEARCH',
  AMAZON: 'AMAZON',
  PAID: 'PAID',
};

export const CATEGORY = {
  PENSION: 'Company Pension',
  DIVIDENDS: 'Dividends',
  SALARY: 'Net salary per Payslip (for non-IR35)',
  ACCOUNTANCY: 'Accountancy',
  BUSINESS_INSURANCE: 'Professional, Employers, & Public Liability Insurance',
  INTERNET_PHONE: 'Internet and Telephone',
  TRAVEL_SUBSISTENCE: 'Travel & Subsistence',
  BANK_FEES: 'Bank Charges and Interest Payable',
  OTHER_COMPUTER_COSTS: 'Other Computer Costs',
  COMPUTER_HARDWARE_OFFICE_EQUIPMENT: 'Computer Hardware and Office Equipment',
  WEBSITE_ADVERTISING: 'Website /Advertising',
  ENTERTAINMENT: 'Business Entertainment',
  SUNDRIES: 'Sundries',
  TRAINING: 'Training',
  STATIONERY_POSTAGE_PRINTING: 'Printing, Postage and Stationery',
  VAT: 'VAT Paid To HMC&E',
};
